name: FastAPI CI/CD

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run tests
      run: pytest

    - name: Lint code
      run: |
        pip install flake8
        flake8 . --count --max-complexity=10 --max-line-length=127 --statistics

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Trigger Render deployment
      env:
        RENDER_SERVICE_ID: ${{ secrets.RENDER_SERVICE_ID }}
        RENDER_API_KEY: ${{ secrets.RENDER_API_KEY }}
      run: |
        curl -X POST \
        -H "Authorization: Bearer $RENDER_API_KEY" \
        -H "Accept: application/json" \
        -d "" \
        https://api.render.com/v1/services/$RENDER_SERVICE_ID/deploys
